services:
  inkplate:
    init: true
    ports:
      - "8080:8080"
      # If you use the MQTT logging, you'll need to uncomment the port below (and change it, if you don't use the same port)
      # - "1883:1883"
    build: 
      context: .
    restart: always
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_MONITOR_ONLY: 'true'
    command: --interval 30 python:slim
