---
server:
  enabled: true
  port: 8080
  aliveSeconds: 60
  maxServes: 1
weather:
  service: accuweather
  apikey: XXXX # CHANGE THIS TO YOUR OWN API KEY
  num_hourly_forecasts: 6
  metric: true
google:
  apikey: XXXX # CHANGE THIS TO YOU OWN API KEY
  staticmaps_mapid: XXXX # CHANGE THIS TO YOUR OWN MAPID
location: Landry, FR
image:
  width: 825
  height: 1200
mqtt:
  enabled: true
  host: localhost
  port: 1883
  topic: mqtt/eink-cal-client