name: Docker Image CI

on:
  push:
    paths:
    - 'server/**'
    - 'Dockerfile'
  pull_request:
    paths:
    - 'server/**'
    - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@latest
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag inkplate10-weather-cal:$(date +%s)
